<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="13.0.0" />
    <PackageReference Include="Microsoft.Extensions.Localization" Version="10.0.9" />
    <PackageReference Include="MiniExcel" Version="1.44.1" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.7.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TemplateProject.Domain\QrAssignment.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\QrApplicants\Queries\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Features\Tenants\Commands\BulkSetActive\BulkSetActiveTenantCommand.cs" />
  </ItemGroup>

</Project>
