<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
	  <NoWarn>$(NoWarn);NU1901</NoWarn>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>c1daaedd-0c85-410f-afb1-65be42d7200f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" /> 
    <PackageReference Include="Azure.Extensions.AspNetCore.DataProtection.Blobs" Version="1.5.4" />
    <PackageReference Include="Azure.Extensions.AspNetCore.DataProtection.Keys" Version="1.6.4" />
    <PackageReference Include="Azure.Identity" Version="1.21.0" />
    <PackageReference Include="MediatR" Version="13.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.OpenApi" Version="2.7.5" />
    <PackageReference Include="Scalar.AspNetCore.Microsoft" Version="2.14.1" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.MSSqlServer" Version="9.0.3" />
    <PackageReference Include="Serilog.UI" Version="3.2.0" />
    <PackageReference Include="Serilog.UI.MsSqlServerProvider" Version="3.2.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TemplateProject.Application\QrAssignment.Application.csproj" />
    <ProjectReference Include="..\TemplateProject.Infrastructure\QrAssignment.Infrastructure.csproj" />
    <ProjectReference Include="..\TemplateProject.Persistance\QrAssignment.Persistance.csproj" />
    <ProjectReference Include="..\TemplateProject.Presentation\QrAssignment.Presentation.csproj" />
  </ItemGroup>

</Project>
