<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <NoWarn>$(NoWarn);NU1901</NoWarn>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.5.1" />
    <PackageReference Include="Microsoft.Extensions.Identity.Stores" Version="10.0.6" />
  </ItemGroup>

</Project>
